export const STEP_EXPORT_CONFIG = {
  rootName: "Everwood Art",
  backboardName: "Backboard",
  squaresName: "Squares",
  squareNamePrefix: "Square",
  squareIdPrefix: "square",
  backboardBodyNamePrefix: "Body",
  filenamePrefix: "everwood-art",
  fileExtension: ".step",
  description: "Editable Everwood Art model exported from the Viewer",
  mediaType: "model/step",
  millimetersPerInch: 25.4,
  inchesPerSceneUnit: 6,
  schema: "AP242DIS",
  stepUnit: "MM",
  assemblyMode: 2,
  documentLengthUnitMeters: 0.001,
  wasmPublicUrl: "/wasm/replicad_with_exceptions.wasm",
  runtimeModulePublicUrl: "/wasm/replicad_with_exceptions.js",
  virtualOutputPath: "/tmp/everwood-art.step",
  componentNumberWidth: 3,
  yearComponentWidth: 4,
  dateComponentWidth: 2,
  firstComponentNumber: 1,
  filenameDateSeparator: "-",
  documentFormat: "BinXCAF",
  stepHeaderImplementationLevel: "2;1",
  stepHeaderAuthor: "Everwood",
  stepHeaderOrganization: "Everwood",
  stepHeaderPreprocessorVersion: "Everwood Palette Viewer",
  stepHeaderOriginatingSystem: "Everwood Palette Viewer",
  stepHeaderAuthorization: "",
  sewingToleranceMillimeters: 0.000001,
  noRotationRadians: 0,
  originCoordinate: 0,
  positiveAxisDirection: 1,
  halfSizeDivisor: 2,
  firstFaceEdgeIndex: 0,
  firstAdditionalFaceEdgeIndex: 1,
  firstBodyIndex: 0,
  ifSelectReturnDone: 1,
  emptyBoundValue: 0,
  colorChannelMax: 255,
  defaultSquareColor: "#FFFFFF",
  defaultErrorMessage: "Unable to generate the STEP file. Please try again.",
} as const;
