export const FUSION_PACKAGE_CONFIG = {
  filenamePrefix: "everwood-art-fusion",
  fileExtension: ".zip",
  mediaType: "application/zip",
  scriptDirectory: "EverwoodAppearance",
  scriptFilename: "EverwoodAppearance.py",
  scriptManifestFilename: "EverwoodAppearance.manifest",
  designManifestFilename: "design-manifest.json",
  readmeFilename: "README.txt",
  textureDirectory: "textures",
  grainAtlasUrl: "/textures/grain-atlas.png",
  plywoodTextureUrl: "/textures/plywood.jpg",
  squareTextureFilenamePrefix: "square",
  backboardTextureFilenamePrefix: "backboard",
  grainTextureFilenameSegment: "grain",
  textureFileExtension: ".png",
  textureMediaType: "image/png",
  textureSizePixels: 256,
  grainIndexWidth: 2,
  scriptId: "99f83c8f-4b47-46b4-9632-a982b5ea2e9e",
  scriptAuthor: "Everwood",
  scriptDescription:
    "Apply Everwood Viewer wood appearances to an imported STEP model.",
  scriptVersion: "1.0.0",
  supportedOperatingSystems: "windows|mac",
  manifestSchemaVersion: 1,
  jsonIndentSpaces: 2,
  zipCompressionLevel: 6,
  firstComponentNumber: 1,
  componentNumberWidth: 3,
  colorChannelMax: 255,
  colorChannelCount: 4,
  rgbChannelCount: 3,
  alphaChannelIndex: 3,
  redHexStartIndex: 1,
  greenHexStartIndex: 3,
  blueHexStartIndex: 5,
  hexChannelLength: 2,
  srgbToLinearThreshold: 0.04045,
  srgbLinearDivisor: 12.92,
  srgbOffset: 0.055,
  srgbScale: 1.055,
  srgbExponent: 2.4,
  linearToSrgbThreshold: 0.0031308,
  minimumColorChannel: 0,
  maximumColorChannel: 1,
  defaultErrorMessage:
    "Unable to build the Fusion package. Please try again.",
} as const;
